##
## vmshift-validator
##
## Two-phase KubeVirt cross-cluster live migration testing:
##   Phase 1: kube-burner density setup
##   Phase 2: selective parallel migration + validation
##

SHELL := /bin/bash
PROJECT_DIR := $(CURDIR)
SCRIPTS_DIR := $(CURDIR)/scripts

# ── Config file (YAML → Make variables via yq) ──────────────────
# Reads config.yaml (gitignored) and generates .config.mk with
# UPPER_SNAKE_CASE ?= value lines. Falls back to defaults below
# when config.yaml is absent. CLI overrides always win.
CONFIG_FILE ?= config.yaml
-include .config.mk

ifneq ($(wildcard $(CONFIG_FILE)),)
.config.mk: $(CONFIG_FILE)
	@echo "# Auto-generated from $(CONFIG_FILE) — do not edit" > $@
	@yq e -o=props '.' $(CONFIG_FILE) | \
		awk -F' = ' '/^[a-z_]/ {print toupper($$1) " ?= " substr($$0, index($$0," = ")+3)}' >> $@
	@echo "Config loaded from $(CONFIG_FILE)"
endif

# ── Cluster authentication ───────────────────────────────────────

# Path to the source (blue) cluster kubeconfig. Used by kubectl/virtctl
# for all source-side operations: VM creation, pre-migration checks,
# migration API calls, and teardown.
SOURCE_KUBECONFIG ?= $(PROJECT_DIR)/config/source-cluster/auth/kubeconfig

# Path to the target (green) cluster kubeconfig. Used by kubectl/virtctl
# for target-side operations: post-migration validation and teardown.
TARGET_KUBECONFIG ?= $(PROJECT_DIR)/config/target-cluster/auth/kubeconfig

# ── VM / namespace settings ──────────────────────────────────────

# Kubernetes namespace where VMs are created by kube-burner and where
# Forklift migrates them to on the target cluster.
NAMESPACE ?= vm-services

# Path to the SSH private key used by virtctl ssh to access guest VMs.
# The matching public key is injected into VMs via cloud-init.
SSH_KEY ?= $(PROJECT_DIR)/keys/kube-burner

# Guest OS username for SSH access. Must match the cloud-init user
# configured in the kube-burner VM template (e.g. fedora, centos, ubuntu).
SSH_USER ?= fedora

# Guest OS password set via cloud-init. Used for console access;
# SSH authentication uses the key pair instead. Only applies to vm-services
# profile (kubevirt-density uses per-OS passwords).
VM_PASSWORD ?= fedora

# SSH public key string injected into VMs via cloud-init ssh_authorized_keys.
# Auto-read from $(SSH_KEY).pub. Override to use a different key pair.
SSH_PUBLIC_KEY ?= $(shell cat $(SSH_KEY).pub 2>/dev/null || echo "")

# Container disk image used as the VM boot disk (vm-services profile only).
# kubevirt-density uses per-VM images (centos, fedora, ubuntu) defined in
# its own config and is not affected by this variable.
CONTAINER_IMAGE ?= quay.io/containerdisks/fedora:41

# Kubernetes node name to pin VMs to via nodeSelector. Leave empty for
# scheduler-placed VMs. Only applies to vm-services profile.
TARGET_NODE ?=

# Label selector used to discover VMs created by kube-burner. Applied to
# kubectl get vm, density-status, discover-vms, and teardown operations.
VM_LABEL_SELECTOR ?= workload-type=services-test

# ── kube-burner settings ────────────────────────────────────────

# Filename of the kube-burner job config inside KUBE_BURNER_DIR.
# Switch to kubevirt-density.yml for the multi-OS density profile.
KUBE_BURNER_CONFIG ?= vm-services.yml

# Directory containing kube-burner job configs and object templates.
# kube-burner runs from this directory so template paths are relative to it.
KUBE_BURNER_DIR ?= $(PROJECT_DIR)/kube-burner

# Name of the rendered config file (auto-generated by render-config target).
# REPLACE_* placeholders in KUBE_BURNER_CONFIG are substituted with Makefile
# variables and written to this file before kube-burner runs.
RENDERED_CONFIG = .rendered-$(KUBE_BURNER_CONFIG)

# ── Forklift / MTV settings ─────────────────────────────────────

# Namespace where Forklift (MTV) operator resources live: Plans, Migrations,
# Providers, NetworkMaps, StorageMaps. Used in migration templates and
# kubectl commands for creating/cleaning migration CRs.
MTV_NAMESPACE ?= openshift-mtv

# Name of the Forklift Provider CR representing the source cluster.
# Must match the Provider resource in MTV_NAMESPACE.
PROVIDER_SOURCE_NAME ?= host

# Name of the Forklift Provider CR representing the target (destination)
# cluster. Must match the Provider resource in MTV_NAMESPACE.
PROVIDER_DEST_NAME ?= green-cluster

# Name of the Forklift NetworkMap CR that defines network mapping between
# source and target clusters. Must exist in MTV_NAMESPACE.
NETWORK_MAP_NAME ?= blue-green-network-map

# Name of the Forklift StorageMap CR that defines storage class mapping
# between source and target clusters. Must exist in MTV_NAMESPACE.
STORAGE_MAP_NAME ?= blue-green-storage-map

# Execution profile for kubectl/virtctl routing. "gcp" uses direct local
# kubeconfig access; "baremetal-l2" routes commands through SSH bastions.
MIGRATION_PROFILE ?= gcp

# Which cluster hosts the Forklift (MTV) operator and CRDs. "source" means
# Plans/Migrations are created on the source cluster; "target" means they
# are created on the target cluster. Controls kubectl_migration routing.
MIGRATION_API ?= source

# Kubernetes StorageClass used for VM data volumes created by kube-burner.
# Substituted into kube-burner configs via render-config.
STORAGE_CLASS ?= standard-csi

# ── Directory paths ─────────────────────────────────────────────

# Base directory for per-run migration reports (summary.json, per-VM logs,
# pre/post migration checks, verdicts). Each run creates a timestamped
# subdirectory: reports/run-<timestamp>/.
REPORTS_DIR ?= $(PROJECT_DIR)/reports

# Directory where migrate-vm.sh writes rendered Forklift Plan/Migration
# YAML manifests after substituting template variables.
GENERATED_DIR ?= $(SCRIPTS_DIR)/generated

# Directory containing Forklift YAML templates (migration-plan.yaml.template,
# migration.yaml.template) with REPLACE_* placeholders.
TEMPLATE_DIR ?= $(PROJECT_DIR)/templates

# ── Windows VM settings ─────────────────────────────────────────

# Name of the golden image PVC to clone for Windows VMs.
WIN_GOLDEN_PVC ?= win2022-golden

# Namespace containing the golden image PVC and OOBE unattend secret.
WIN_GOLDEN_NAMESPACE ?= windows-golden-images

# Name of the Secret containing unattend.xml for Windows OOBE auto-completion.
WIN_OOBE_SECRET ?= win2022-oobe-unattend

# Root disk size for cloned Windows VMs.
WIN_ROOT_DISK_SIZE ?= 40Gi

# Max seconds to wait for QEMU guest agent readiness on Windows VMs.
GA_READY_TIMEOUT ?= 300

# Seconds between guest agent readiness polls.
GA_READY_INTERVAL ?= 15

# ── Prometheus metric capture ──────────────────────────────────

# Enable Prometheus metric capture during migration (true/false).
PROM_ENABLED ?= true

# Namespace where Prometheus runs (openshift-monitoring on OCP).
PROM_NAMESPACE ?= openshift-monitoring

# Pod name for kubectl exec into Prometheus.
PROM_POD ?= prometheus-k8s-0

# Container within the Prometheus pod.
PROM_CONTAINER ?= prometheus

# Prometheus localhost URL inside the pod.
PROM_URL ?= http://localhost:9090

# Step interval for Prometheus range queries.
PROM_RANGE_STEP ?= 15s

# ── Timeouts and tuning ─────────────────────────────────────────

# Logging verbosity for scripts (1=info, 2=verbose, 3=debug).
# Controls output from lib/log.sh helpers.
LOG_LEVEL ?= 1

# Seconds to wait after kube-burner completes before verifying that
# in-guest workloads (file-writer, sqlite-writer) have started producing data.
STABILIZE_WAIT ?= 30

# Max seconds to wait for guest SSH to become reachable via virtctl ssh
# during density-setup and pre-migration checks.
SSH_READY_TIMEOUT ?= 600

# Max seconds to wait for guest SSH on the target cluster after migration.
# Shorter than SSH_READY_TIMEOUT because the VM should boot faster post-migration.
POST_SSH_READY_TIMEOUT ?= 225

# Extra options passed to virtctl ssh --local-ssh-opts. Useful for disabling
# host key checking or setting connection timeouts in specific environments.
LOCAL_SSH_OPTS ?=

# Max number of polling iterations when waiting for a Forklift Migration to
# complete. Total timeout = MAX_ATTEMPTS * POLL_INTERVAL seconds.
MIGRATION_MAX_ATTEMPTS ?= 60

# Seconds between status polls while waiting for a Forklift Migration to
# reach Completed or Failed phase.
MIGRATION_POLL_INTERVAL ?= 10

# Seconds to sleep before applying Forklift migration CRs. Use with chaos
# testing to give krknctl time to start before migration begins.
# Example: make migrate-selective VMS=vm-0 PRE_MIGRATE_DELAY=10
PRE_MIGRATE_DELAY ?=

# Human-readable tag prepended to the report run directory name.
# Example: make migrate-selective VMS=vm-0 RUN_TAG=A1-iteration1
#   creates reports/run-A1-iteration1-20260702T120400Z/
RUN_TAG ?=

# ── Required CLI tools ──────────────────────────────────────────

# List of CLI binaries required on the host. Checked by the check-prereqs
# target before any operations run.
REQUIRED_TOOLS := kubectl virtctl kube-burner jq yq python3

# ── Derived ─────────────────────────────────────────────────────
COMMON_ARGS := \
	--namespace $(NAMESPACE) \
	--ssh-key $(SSH_KEY) \
	--ssh-user $(SSH_USER) \
	--local-ssh-opts "$(LOCAL_SSH_OPTS)"

export MIGRATION_API
export PROM_ENABLED PROM_NAMESPACE PROM_POD PROM_CONTAINER PROM_URL PROM_RANGE_STEP

MIGRATION_ARGS := \
	--mtv-namespace $(MTV_NAMESPACE) \
	--migration-profile $(MIGRATION_PROFILE) \
	--post-ssh-timeout $(POST_SSH_READY_TIMEOUT) \
	--max-attempts $(MIGRATION_MAX_ATTEMPTS) \
	--poll-interval $(MIGRATION_POLL_INTERVAL) \
	$(if $(PRE_MIGRATE_DELAY),--pre-migrate-delay $(PRE_MIGRATE_DELAY),) \
	$(if $(RUN_TAG),--run-tag $(RUN_TAG),)

.PHONY: help \
	init-config \
	check-prereqs check-clusters check-forklift \
	generate-keys setup-kubeconfigs render-config \
	density-setup density-status density-teardown \
	discover-vms migrate-selective migrate-dry-run \
	report list-reports fetch-reports logs \
	reauth-blue \
	ssh status \
	clean-migrations clean-generated clean-reports clean-logs clean-all \
	e2e

# ═══════════════════════════════════════════════════════════════
#  Help
# ═══════════════════════════════════════════════════════════════

help: ## Show help
	@echo ""
	@echo "vmshift-validator"
	@echo "================="
	@echo ""
	@echo "Setup & Validation:"
	@echo "  make init-config                Copy config.example.yaml → config.yaml"
	@echo "  make check-prereqs              Verify CLI tools, kubeconfigs, SSH key"
	@echo "  make check-clusters             Test connectivity to both clusters"
	@echo "  make check-forklift             Verify Forklift/MTV CRDs and mappings"
	@echo "  make generate-keys              Generate SSH key pair for VM access"
	@echo "  make setup-kubeconfigs           Copy kubeconfigs (SOURCE_KC=... TARGET_KC=...)"
	@echo "  make render-config              Render kube-burner config from template"
	@echo ""
	@echo "Phase 1 - Density:"
	@echo "  make density-setup              Create VMs via kube-burner"
	@echo "  make density-setup KUBE_BURNER_CONFIG=vm-services-heavy.yml"
	@echo "                                  Create VMs with memory-heavy workloads"
	@echo "  make density-setup KUBE_BURNER_CONFIG=vm-windows.yml"
	@echo "                                  Create Windows VMs from golden image"
	@echo "  make density-status             Show VM status on source"
	@echo "  make density-teardown           Remove VMs from both clusters"
	@echo ""
	@echo "Phase 2 - Selective migration:"
	@echo "  make discover-vms               List VMs available for migration"
	@echo "  make migrate-selective VMS=vm-a-0,vm-b-0"
	@echo "  make migrate-selective N=3"
	@echo "  make migrate-selective SELECTOR=vm-size=large"
	@echo "  make migrate-dry-run VM=name    Render manifests without applying"
	@echo ""
	@echo "Reports & Logs:"
	@echo "  make report                     Show latest summary"
	@echo "  make list-reports               List report runs"
	@echo "  make fetch-reports              Fetch reports from bastion"
	@echo "  make fetch-reports RUN_ID=...   Fetch a specific run"
	@echo "  make logs                       Show latest kube-burner log"
	@echo ""
	@echo "Auth:"
	@echo "  make reauth-blue                Reauthenticate blue cluster (baremetal-l2)"
	@echo ""
	@echo "Cleanup:"
	@echo "  make clean-migrations           Delete Forklift CRs"
	@echo "  make clean-generated            Remove rendered manifests"
	@echo "  make clean-reports              Remove all report directories"
	@echo "  make clean-logs                 Remove kube-burner logs"
	@echo "  make clean-all                  Full cleanup (migrations + VMs + generated)"
	@echo ""
	@echo "End-to-end:"
	@echo "  make e2e                        Full run: prereqs -> setup -> migrate -> report"
	@echo ""
	@echo "Variables:"
	@echo "  Cluster:    SOURCE_KUBECONFIG  TARGET_KUBECONFIG  NAMESPACE"
	@echo "  SSH:        SSH_KEY  SSH_USER  SSH_PUBLIC_KEY  VM_PASSWORD"
	@echo "  VM:         CONTAINER_IMAGE  TARGET_NODE  VM_LABEL_SELECTOR  STORAGE_CLASS"
	@echo "  Migration:  MIGRATION_PROFILE  MTV_NAMESPACE  PROVIDER_SOURCE_NAME  PROVIDER_DEST_NAME"
	@echo "              NETWORK_MAP_NAME  STORAGE_MAP_NAME"
	@echo "  Tuning:     LOG_LEVEL  STABILIZE_WAIT  SSH_READY_TIMEOUT  POST_SSH_READY_TIMEOUT"
	@echo "              MIGRATION_MAX_ATTEMPTS  MIGRATION_POLL_INTERVAL"
	@echo "  Windows:    WIN_GOLDEN_PVC  WIN_GOLDEN_NAMESPACE  WIN_OOBE_SECRET  WIN_ROOT_DISK_SIZE"
	@echo "  Prometheus: PROM_ENABLED  PROM_NAMESPACE  PROM_POD  PROM_RANGE_STEP"
	@echo "              GA_READY_TIMEOUT  GA_READY_INTERVAL"
	@echo "  Tags:       RUN_TAG  RUN_ID"
	@echo "  Selectors:  VMS  N  SELECTOR  KUBE_BURNER_CONFIG"
	@echo ""
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2}'
	@echo ""

# ═══════════════════════════════════════════════════════════════
#  Setup & Validation
# ═══════════════════════════════════════════════════════════════

init-config: ## Copy config.example.yaml to config.yaml for editing
	@if [[ -f "$(CONFIG_FILE)" ]]; then \
		echo "$(CONFIG_FILE) already exists — refusing to overwrite."; \
		echo "  Remove it first or edit it directly."; \
		exit 1; \
	fi
	@cp config.example.yaml $(CONFIG_FILE)
	@echo "Created $(CONFIG_FILE) from config.example.yaml"
	@echo "Edit it with your environment-specific values, then re-run make."

check-prereqs: ## Verify CLI tools, kubeconfigs, and SSH key
	@echo "Checking CLI tools..."
	@MISSING=0; \
	for tool in $(REQUIRED_TOOLS); do \
		if ! command -v $$tool >/dev/null 2>&1; then \
			echo "  MISSING: $$tool"; MISSING=1; \
		else \
			echo "  OK: $$tool ($$($$tool version 2>/dev/null | head -1 || echo 'available'))"; \
		fi; \
	done; \
	echo ""; \
	echo "Checking files..."; \
	[[ -f "$(SOURCE_KUBECONFIG)" ]] && echo "  OK: source kubeconfig" || { echo "  MISSING: $(SOURCE_KUBECONFIG)"; MISSING=1; }; \
	[[ -f "$(TARGET_KUBECONFIG)" ]] && echo "  OK: target kubeconfig" || { echo "  MISSING: $(TARGET_KUBECONFIG)"; MISSING=1; }; \
	[[ -f "$(SSH_KEY)" ]]           && echo "  OK: SSH private key"   || { echo "  MISSING: $(SSH_KEY)"; MISSING=1; }; \
	[[ -f "$(SSH_KEY).pub" ]]       && echo "  OK: SSH public key"    || { echo "  MISSING: $(SSH_KEY).pub"; MISSING=1; }; \
	[[ -f "$(KUBE_BURNER_DIR)/$(KUBE_BURNER_CONFIG)" ]] && echo "  OK: kube-burner config" || { echo "  MISSING: $(KUBE_BURNER_DIR)/$(KUBE_BURNER_CONFIG)"; MISSING=1; }; \
	echo ""; \
	if [[ $$MISSING -ne 0 ]]; then echo "Some prerequisites are missing."; exit 1; fi; \
	echo "All prerequisites satisfied."

check-clusters: ## Verify connectivity to source and target clusters
	@echo "=== Source Cluster ==="
	@KUBECONFIG=$(SOURCE_KUBECONFIG) kubectl cluster-info 2>/dev/null || { echo "UNREACHABLE"; exit 1; }
	@echo ""
	@echo "=== Target Cluster ==="
	@KUBECONFIG=$(TARGET_KUBECONFIG) kubectl cluster-info 2>/dev/null || { echo "UNREACHABLE"; exit 1; }

check-forklift: ## Verify Forklift/MTV CRDs and provider mappings
	$(eval FORKLIFT_KC := $(if $(filter target,$(MIGRATION_API)),$(TARGET_KUBECONFIG),$(SOURCE_KUBECONFIG)))
	@echo "Checking Forklift CRDs (MIGRATION_API=$(MIGRATION_API))..."
	@KUBECONFIG=$(FORKLIFT_KC) kubectl get crd plans.forklift.konveyor.io >/dev/null 2>&1 || \
		{ echo "ERROR: Forklift Plan CRD not found"; exit 1; }
	@KUBECONFIG=$(FORKLIFT_KC) kubectl get crd migrations.forklift.konveyor.io >/dev/null 2>&1 || \
		{ echo "ERROR: Forklift Migration CRD not found"; exit 1; }
	@echo "  CRDs: OK"
	@echo ""
	@echo "Checking provider mappings in $(MTV_NAMESPACE)..."
	@KUBECONFIG=$(FORKLIFT_KC) kubectl get networkmap $(NETWORK_MAP_NAME) -n $(MTV_NAMESPACE) >/dev/null 2>&1 && \
		echo "  NetworkMap '$(NETWORK_MAP_NAME)': OK" || \
		echo "  WARNING: NetworkMap '$(NETWORK_MAP_NAME)' not found in $(MTV_NAMESPACE)"
	@KUBECONFIG=$(FORKLIFT_KC) kubectl get storagemap $(STORAGE_MAP_NAME) -n $(MTV_NAMESPACE) >/dev/null 2>&1 && \
		echo "  StorageMap '$(STORAGE_MAP_NAME)': OK" || \
		echo "  WARNING: StorageMap '$(STORAGE_MAP_NAME)' not found in $(MTV_NAMESPACE)"
	@echo ""
	@echo "Checking providers..."
	@KUBECONFIG=$(FORKLIFT_KC) kubectl get provider $(PROVIDER_SOURCE_NAME) -n $(MTV_NAMESPACE) >/dev/null 2>&1 && \
		echo "  Source provider '$(PROVIDER_SOURCE_NAME)': OK" || \
		echo "  WARNING: Source provider '$(PROVIDER_SOURCE_NAME)' not found in $(MTV_NAMESPACE)"
	@KUBECONFIG=$(FORKLIFT_KC) kubectl get provider $(PROVIDER_DEST_NAME) -n $(MTV_NAMESPACE) >/dev/null 2>&1 && \
		echo "  Dest provider '$(PROVIDER_DEST_NAME)': OK" || \
		echo "  WARNING: Dest provider '$(PROVIDER_DEST_NAME)' not found in $(MTV_NAMESPACE)"
	@echo ""
	@echo "Forklift check complete."

generate-keys: ## Generate SSH key pair for VM access
	@mkdir -p $(PROJECT_DIR)/keys
	@if [[ -f "$(SSH_KEY)" ]]; then \
		echo "SSH key already exists: $(SSH_KEY)"; \
	else \
		ssh-keygen -t ed25519 -f $(SSH_KEY) -N "" -C "kube-burner-vm"; \
		echo "SSH key generated: $(SSH_KEY)"; \
	fi

setup-kubeconfigs: ## Copy kubeconfigs into place (SOURCE_KC=... TARGET_KC=...)
ifndef SOURCE_KC
	$(error Provide SOURCE_KC=/path/to/source/kubeconfig TARGET_KC=/path/to/target/kubeconfig)
endif
ifndef TARGET_KC
	$(error Provide TARGET_KC=/path/to/target/kubeconfig)
endif
	@mkdir -p $(PROJECT_DIR)/config/source-cluster/auth $(PROJECT_DIR)/config/target-cluster/auth
	@cp $(SOURCE_KC) $(SOURCE_KUBECONFIG)
	@cp $(TARGET_KC) $(TARGET_KUBECONFIG)
	@echo "Kubeconfigs installed."
	@echo "  Source: $(SOURCE_KUBECONFIG)"
	@echo "  Target: $(TARGET_KUBECONFIG)"

render-config: ## Render kube-burner config by substituting Makefile variables
	@if echo "$(KUBE_BURNER_CONFIG)" | grep -qv windows; then \
		if [[ -z "$(SSH_PUBLIC_KEY)" ]]; then \
			echo "ERROR: SSH_PUBLIC_KEY is empty. Run 'make generate-keys' first or set SSH_PUBLIC_KEY=..."; \
			exit 1; \
		fi; \
	fi
	@sed \
		-e 's|REPLACE_SSH_PUBLIC_KEY|$(SSH_PUBLIC_KEY)|g' \
		-e 's|REPLACE_SSH_USER|$(SSH_USER)|g' \
		-e 's|REPLACE_VM_PASSWORD|$(VM_PASSWORD)|g' \
		-e 's|REPLACE_STORAGE_CLASS|$(STORAGE_CLASS)|g' \
		-e 's|REPLACE_CONTAINER_IMAGE|$(CONTAINER_IMAGE)|g' \
		-e 's|REPLACE_TARGET_NODE|$(TARGET_NODE)|g' \
		-e 's|REPLACE_WIN_GOLDEN_PVC|$(WIN_GOLDEN_PVC)|g' \
		-e 's|REPLACE_WIN_GOLDEN_NAMESPACE|$(WIN_GOLDEN_NAMESPACE)|g' \
		-e 's|REPLACE_WIN_OOBE_SECRET|$(WIN_OOBE_SECRET)|g' \
		-e 's|REPLACE_WIN_ROOT_DISK_SIZE|$(WIN_ROOT_DISK_SIZE)|g' \
		"$(KUBE_BURNER_DIR)/$(KUBE_BURNER_CONFIG)" \
		> "$(KUBE_BURNER_DIR)/$(RENDERED_CONFIG)"
	@echo "Rendered: $(KUBE_BURNER_DIR)/$(RENDERED_CONFIG)"

# ═══════════════════════════════════════════════════════════════
#  Phase 1 — Density
# ═══════════════════════════════════════════════════════════════

density-setup: render-config ## Run kube-burner and stabilize workloads
	@LOG_LEVEL=$(LOG_LEVEL) GA_READY_TIMEOUT=$(GA_READY_TIMEOUT) GA_READY_INTERVAL=$(GA_READY_INTERVAL) $(SCRIPTS_DIR)/density-setup.sh \
		--kubeconfig $(SOURCE_KUBECONFIG) \
		--config $(RENDERED_CONFIG) \
		--kube-burner-dir $(KUBE_BURNER_DIR) \
		--namespace $(NAMESPACE) \
		--ssh-key $(SSH_KEY) \
		--ssh-user $(SSH_USER) \
		--label-selector $(VM_LABEL_SELECTOR) \
		--stabilize-wait $(STABILIZE_WAIT) \
		--ssh-ready-timeout $(SSH_READY_TIMEOUT) \
		$(if $(LOCAL_SSH_OPTS),--local-ssh-opts "$(LOCAL_SSH_OPTS)",)

density-status: ## Show density VM status on source cluster
	@$(SCRIPTS_DIR)/density-status.sh \
		--kubeconfig $(SOURCE_KUBECONFIG) \
		--namespace $(NAMESPACE) \
		--label-selector $(VM_LABEL_SELECTOR)

density-teardown: ## Remove density VMs and migration CRs
	@LOG_LEVEL=$(LOG_LEVEL) $(SCRIPTS_DIR)/density-teardown.sh \
		--source-kubeconfig $(SOURCE_KUBECONFIG) \
		--target-kubeconfig $(TARGET_KUBECONFIG) \
		--namespace $(NAMESPACE) \
		--label-selector $(VM_LABEL_SELECTOR) \
		--kube-burner-dir $(KUBE_BURNER_DIR) \
		--config $(KUBE_BURNER_CONFIG) \
		--mtv-namespace $(MTV_NAMESPACE)

# ═══════════════════════════════════════════════════════════════
#  Phase 2 — Migration
# ═══════════════════════════════════════════════════════════════

discover-vms: ## List VMs available for migration
	@$(SCRIPTS_DIR)/discover-vms.sh \
		--kubeconfig $(SOURCE_KUBECONFIG) \
		--namespace $(NAMESPACE) \
		--label-selector $(VM_LABEL_SELECTOR)

migrate-selective: ## Migrate selected VMs in parallel (VMS=, N=, or SELECTOR=)
	@set -e; \
	n=0; \
	[[ -n "$(VMS)" ]] && n=$$((n+1)); \
	[[ -n "$(N)" ]] && n=$$((n+1)); \
	[[ -n "$(SELECTOR)" ]] && n=$$((n+1)); \
	if [[ $$n -ne 1 ]]; then \
	  echo "ERROR: specify exactly one of VMS=..., N=..., or SELECTOR=..."; exit 1; \
	fi; \
	LOG_LEVEL=$(LOG_LEVEL) $(SCRIPTS_DIR)/migrate-parallel.sh \
		--source-kubeconfig $(SOURCE_KUBECONFIG) \
		--target-kubeconfig $(TARGET_KUBECONFIG) \
		$(COMMON_ARGS) \
		--ssh-ready-timeout $(SSH_READY_TIMEOUT) \
		--provider-source $(PROVIDER_SOURCE_NAME) \
		--provider-dest $(PROVIDER_DEST_NAME) \
		--network-map $(NETWORK_MAP_NAME) \
		--storage-map $(STORAGE_MAP_NAME) \
		--base-selector $(VM_LABEL_SELECTOR) \
		$(MIGRATION_ARGS) \
		$(if $(VMS),--vms "$(VMS)",) \
		$(if $(N),--count $(N),) \
		$(if $(SELECTOR),--selector "$(SELECTOR)",)

migrate-dry-run: ## Render migration manifests without applying (VM=name)
ifndef VM
	$(error Specify VM=vm-name)
endif
	$(eval FORKLIFT_KC := $(if $(filter target,$(MIGRATION_API)),$(TARGET_KUBECONFIG),$(SOURCE_KUBECONFIG)))
	@$(SCRIPTS_DIR)/migrate-vm.sh \
		--kubeconfig $(FORKLIFT_KC) \
		--vm $(VM) \
		--namespace $(NAMESPACE) \
		--template-dir $(TEMPLATE_DIR) \
		--output-dir $(GENERATED_DIR) \
		--provider-source $(PROVIDER_SOURCE_NAME) \
		--provider-dest $(PROVIDER_DEST_NAME) \
		--network-map $(NETWORK_MAP_NAME) \
		--storage-map $(STORAGE_MAP_NAME) \
		--mtv-namespace $(MTV_NAMESPACE) \
		--dry-run

# ═══════════════════════════════════════════════════════════════
#  Reports & Logs
# ═══════════════════════════════════════════════════════════════

report: ## Show latest migration summary
	@LATEST=$$(ls -td $(REPORTS_DIR)/run-* 2>/dev/null | head -1); \
	if [[ -z "$$LATEST" ]]; then echo "No reports found."; exit 0; fi; \
	if [[ -f "$$LATEST/summary.json" ]]; then jq . "$$LATEST/summary.json"; else echo "No summary in $$LATEST"; fi

list-reports: ## List all report runs
	@ls -lt $(REPORTS_DIR)/run-* 2>/dev/null || echo "No reports found."

pull-reports: ## Pull reports from remote bastion to local machine
	@./pull-reports.sh

logs: ## Show latest kube-burner log
	@LATEST=$$(ls -t $(KUBE_BURNER_DIR)/kube-burner-*.log 2>/dev/null | head -1); \
	if [[ -n "$$LATEST" ]]; then cat "$$LATEST"; else echo "No kube-burner logs found."; fi

fetch-reports: ## Fetch reports from bastion to local reports/
	@$(SCRIPTS_DIR)/fetch-reports.sh --profile $(MIGRATION_PROFILE) \
		$(if $(RUN_ID),--run-id $(RUN_ID),)

# ═══════════════════════════════════════════════════════════════
#  Interactive
# ═══════════════════════════════════════════════════════════════

ssh: ## SSH into VM (VM=name CLUSTER=source|target)
ifndef VM
	$(error Specify VM=vm-name)
endif
	@if [[ "$(CLUSTER)" == "target" ]]; then \
		KUBECONFIG=$(TARGET_KUBECONFIG) virtctl ssh $(SSH_USER)@vm/$(VM) \
			--namespace $(NAMESPACE) --identity-file=$(SSH_KEY); \
	else \
		KUBECONFIG=$(SOURCE_KUBECONFIG) virtctl ssh $(SSH_USER)@vm/$(VM) \
			--namespace $(NAMESPACE) --identity-file=$(SSH_KEY); \
	fi

reauth-blue: ## Reauthenticate blue (source) cluster via oc login (baremetal-l2)
	@PROFILE_ENV="$(PROJECT_DIR)/profiles/baremetal-l2.env"; \
	if [[ ! -f "$$PROFILE_ENV" ]]; then \
		echo "ERROR: $$PROFILE_ENV not found."; \
		echo "  cp profiles/baremetal-l2.env.example profiles/baremetal-l2.env"; \
		exit 1; \
	fi; \
	source "$$PROFILE_ENV"; \
	if [[ -z "$$BLUE_API_URL" || -z "$$BLUE_USERNAME" || -z "$$BLUE_PASSWORD" ]]; then \
		echo "ERROR: BLUE_API_URL, BLUE_USERNAME, BLUE_PASSWORD must be set in $$PROFILE_ENV"; \
		exit 1; \
	fi; \
	echo "Logging in to blue cluster: $$BLUE_API_URL"; \
	oc login "$$BLUE_API_URL" \
		--username "$$BLUE_USERNAME" \
		--password "$$BLUE_PASSWORD" \
		--insecure-skip-tls-verify \
		--kubeconfig "$$SOURCE_BASTION_KUBECONFIG"; \
	echo "Blue cluster reauthenticated. Kubeconfig: $$SOURCE_BASTION_KUBECONFIG"

status: ## Show VM on both clusters (VM=name)
ifndef VM
	$(error Specify VM=vm-name)
endif
	@echo "=== SOURCE ==="
	@KUBECONFIG=$(SOURCE_KUBECONFIG) kubectl get vm,vmi $(VM) -n $(NAMESPACE) 2>/dev/null || echo "Not found"
	@echo ""
	@echo "=== TARGET ==="
	@KUBECONFIG=$(TARGET_KUBECONFIG) kubectl get vm,vmi $(VM) -n $(NAMESPACE) 2>/dev/null || echo "Not found"

# ═══════════════════════════════════════════════════════════════
#  Cleanup
# ═══════════════════════════════════════════════════════════════

clean-migrations: ## Delete Forklift Plan/Migration CRs
	@KUBECONFIG=$(TARGET_KUBECONFIG) kubectl delete migration --all -n $(MTV_NAMESPACE) --ignore-not-found 2>/dev/null || true
	@KUBECONFIG=$(TARGET_KUBECONFIG) kubectl delete plan --all -n $(MTV_NAMESPACE) --ignore-not-found 2>/dev/null || true
	@echo "Migration CRs cleaned."

clean-generated: ## Remove rendered migration manifests
	@rm -rf $(GENERATED_DIR)/*.yaml
	@echo "Generated manifests cleaned."

clean-reports: ## Remove all report directories
	@rm -rf $(REPORTS_DIR)/run-*
	@echo "Reports cleaned."

clean-logs: ## Remove kube-burner logs
	@rm -f $(KUBE_BURNER_DIR)/kube-burner-*.log
	@rm -f $(KUBE_BURNER_DIR)/.rendered-*.yml
	@echo "Kube-burner logs and rendered configs cleaned."

clean-all: clean-migrations clean-generated clean-logs density-teardown ## Full cleanup

# ═══════════════════════════════════════════════════════════════
#  End-to-end
# ═══════════════════════════════════════════════════════════════

e2e: check-prereqs density-setup migrate-selective report ## Full run: prereqs -> setup -> migrate -> report

.DEFAULT_GOAL := help
