global:
  measurements:
  - name: vmiLatency

jobs:
  - name: vm-services
    jobType: create
    jobIterations: 1
    qps: 5
    burst: 5
    namespacedIterations: false
    namespace: vm-services
    verifyObjects: true
    errorOnVerify: true
    jobIterationDelay: 1s
    waitWhenFinished: true
    podWait: false
    maxWaitTimeout: 30m
    jobPause: 3m
    cleanup: true
    objects:

    # 5 small Fedora VMs spread by scheduler
    - objectTemplate: templates/vm-services.yml
      replicas: 5
      inputVars:
        name: vm-svc
        image: REPLACE_CONTAINER_IMAGE
        user: REPLACE_SSH_USER
        password: REPLACE_VM_PASSWORD
        osLabel: fedora
        sizeLabel: small
        cpuCores: 1
        memory: 512Mi
        storageSize: 5Gi
        storageClassName: REPLACE_STORAGE_CLASS
        sshPublicKey: REPLACE_SSH_PUBLIC_KEY
        targetNode: "REPLACE_TARGET_NODE"
